-- Signals table
-- Stores trading signals/alerts

CREATE TYPE signal_type AS ENUM (
  'new_position',
  'position_increase',
  'position_close',
  'cluster_convergence',
  'unusual_size',
  'high_score_entry'
);

CREATE TABLE IF NOT EXISTS signals (
  id BIGSERIAL PRIMARY KEY,
  signal_type signal_type NOT NULL,
  wallets TEXT[] NOT NULL,
  coin TEXT,
  direction TEXT CHECK (direction IN ('long', 'short')),
  confidence DECIMAL(5, 4) NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN NOT NULL DEFAULT true
);

-- Comments
COMMENT ON TABLE signals IS 'Trading signals generated by the system';
COMMENT ON COLUMN signals.wallets IS 'Wallets involved in this signal';
COMMENT ON COLUMN signals.confidence IS 'Signal confidence, 0 to 1';
